# Use an official Node runtime as a parent image
FROM node:18.17.1 AS build

# Set the working directory
WORKDIR /app

# Copy the application to the working directory
COPY . .

# Install the dependencies	
RUN npm install

# Build the application
RUN npm run build

# Use an official nginx image as the base image for serving the app
FROM nginx:alpine

# Copy the built app from the previous stage to the nginx html directory
COPY --from=build /app/dist /usr/share/nginx/html

# Copy nginx configuration file
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose the port that nginx will run on within the container, NOT THE PORT WE CONNECT TO ON externally
EXPOSE 80 

# Start nginx
CMD ["nginx", "-g", "daemon off;"]
